version: "3.9"

services:
  api:
    container_name: mybook_app
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mysql_db
    restart: always
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mybook_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_NAME=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}

